# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-28 06:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Huser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('fb_id', models.BigIntegerField(default=-1)),
                ('g_id', models.BigIntegerField(default=-1)),
                ('city_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Cities')),
                ('state_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.StatesUT')),
            ],
            options={
                'db_table': 'User',
                'managed': True,
            },
        ),
    ]
