# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-28 05:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('place_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
            ],
            options={
                'db_table': 'Cities',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='StatesUT',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('place_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
            ],
            options={
                'db_table': 'StatesUT',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='cities',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.StatesUT'),
        ),
    ]
